feign:
    sentinel:
        enabled: true
server:
    port: 18087
spring:
    application:
        name: index-service
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: localhost:8848
                username: nacos
        sentinel:
            eager: true
            transport:
                dashboard: localhost:8080
                port: 8719

    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: http://localhost:9411
        discovery-client-enabled: true
        sender:
            type: web
    thymeleaf:
        cache: false
    redis:
        host: 192.168.227.128

