server:
    port: 8888
spring:
    application:
        name: gmall-gateway
    cloud:
        nacos:
            discovery:
                namespace: public
                password: nacos
                server-addr: localhost:8848
                username: nacos
        gateway:
          routes:
            - id: pms-route
              uri: lb://pms-service
              predicates:
                - Path=/pms/**
            - id: wms-route
              uri: lb://wms-service
              predicates:
                - Path=/wms/**
            - id: sms-route
              uri: lb://sms-service
              predicates:
                - Path=/sms/**
            - id: ums-route
              uri: lb://ums-service
              predicates:
                - Path=/ums/**
            - id: oms-route
              uri: lb://oms-service
              predicates:
                - Path=/oms/**