feign:
    sentinel:
        enabled: true
server:
    port: 18089
spring:
    application:
        name: auth-service
    cloud:
        nacos:
            discovery:
                password: nacos
                server-addr: localhost:8848
                username: nacos
        sentinel:
            eager: true
            transport:
                dashboard: localhost:8080
                port: 8719
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: http://localhost:9411
        discovery-client-enabled: true
        sender:
            type: web
jwt:
    pubKeyPath: D:\日志\密钥\rsa.pub
    priKeyPath: D:\日志\密钥\rsa.pri
    secret: 30489ouerweljrLROE@#)(@$*343jlsdf
    cookieName: GMALL-TOKEN
    expire: 180
    unick: unick
