feign:
    sentinel:
        enabled: true
mybatis-plus:
    global-config:
        db-config:
            id-type: auto
    mapper-locations: classpath:mapper/wms/*.xml
    type-aliases-package: com.atguigu.gmall.wms.entity
server:
    port: 18083
spring:
    application:
        name: wms-service
    cloud:
        nacos:
            discovery:
                password: nacos
                server-addr: localhost:8848
                username: nacos
        sentinel:
            eager: true
            transport:
                dashboard: localhost:8080
                port: 8719
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        name: defaultDataSource
        password: root
        url: jdbc:mysql://localhost:3306/guli_wms?serverTimezone=UTC
        username: root
    redis:
        host: 192.168.227.128
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: http://localhost:9411
        discovery-client-enabled: true
        sender:
            type: web
